@startuml title Data base design

    entity User {
    - Id : int
    - Name : string
    - Email: string
    - ActualExpense: decimal
    - GoalExpense: decimal
    - PasswordHash: string
    - CreatedAt: date
    }
  
    
    entity ExpenseTracker {
    - Id : int
    - UserId : int
    - Amount: decimal
    - Description: string
    - ExpenseCategoryId: int
    - Date : date
    - CreatedAt: date
    }
    
    entity IncomeTracker {
    - Id : int
    - UserId : int
    - Amount: decimal
    - Source: string
    - Date : date
    - CreatedAt: date
    }

    entity ExpenseCategory {
    - Id : int
    - Name: string
    }

    entity UserGoals {
    - UserId : int
    - ExpectBudgeting: int
    - ActualBudgeting: int
    - ExpectIncomeGoal: int
    - ActualIncomeGoal: int
    }
    
    entity Budgdet {
    - Id : int
    - UserId : int
    - Month: date
    - BudgetAmount: decimal
    }
    
    entity Goal {
    - Id : int
    - UserId : int
    - GoalAmount: decimal
    - DeadLine: date
    - CurrentAmount : decimal
    - CreatedAt: date
    }
 
 
User }o-- ExpenseTracker
User }o-- IncomeTracker 
User }o-- UserGoals 
ExpenseTracker }o-- ExpenseCategory 
User ||-- Budgdet : has a
User }o-- Goal 


@enduml
