@startuml ExpenseTracker

  Domain.UserItems --* Persistence.ApplicationDbContext
  Domain.UserGoals --* Persistence.ApplicationDbContext
  Persistence.DbInitializer --* RequestPipeLine.WebApplicationExtension
  Domain.Expense --* API.ExpensesService : use
  Domain.Income --* API.IncomeService  : use
  User.UserManager --> Domain.User : manages 
  User.UserService --> Domain.User : operates on
  Mapper.CreateUserRequest --o Controllers.UserController
  Mapper.CreateExpenseRequest --o Controllers.ExpenseController
  Mapper.CreateIncomeRequest --o Controllers.IncomeController
  
package "Domain" {
  class Expense {
   - id : Guid
   - amount : Decimal
   - date : Date 
   - description : String
   - category : ExpenseCategory
  }
  
  class ExpenseCategory {
   - id : Guid
   - Name : String
  }
  
  class Income {
   - id : Guid
   - amount : Decimal
   - date : Date 
   - source : String
  }
  
  class UserItems {
    + UserId : Guid
    + Expenses : [Expense]
    + Incomes : [Income] 
    + ExpensesCategory : [ExpensesCategory]
  }
  
  class UserGoals {
    + UserId : Guid 
    + ExpectBudgeting : Decimal
    + ActualBudgeting : Decimal
    + ExpectIncomeGoal : Decimal
    + ActualIncomeGoal : Decimal
  }
  
  class User {
    + Id : Guid
    + Name : String 
    + Email : String 
    + Password : String 
  }
  
  
  ExpenseCategory --* Expense
  Expense --o UserItems
  ExpenseCategory --o UserItems
  Income --o UserItems
}  
  
  
package "Mapper" {

  interface CreateRequestTemplate {
    + ToDomain(): T 
  }

  class CreateExpenseRequest {
   - amount : Decimal
   - date : Date 
   - description : String
   - category : ExpenseCategory
   + ToDomain(): Expense
  } 
  
  class CreateIncomeRequest {
   - amount : Decimal
   - date : Date 
   - source : String
   + ToDomain(): Income
  }
  
  class CreateUserRequest {
    + Name : String 
    + Email : String 
    + Password : String 
    + ToDomain(): User 
  }
  
  CreateRequestTemplate --> CreateExpenseRequest : Implement
  CreateRequestTemplate --> CreateIcomeRequest : Implement
  CreateRequestTemplate --> CreateUserRequest : Implement
}

package "API" {
  
  interface BaseService {
    + Context : ApplicationDbContext
    + Create(T) : bool
    + Read() : [T]
    + Update(Guid, T) : bool
    + Delete(Guid) : bool
  }
  
  class ExpensesService {
    + Context : ApplicationDbContext
    + Create(Expense) : bool
    + Read() : [Expense]
    + Update(Guid, Expense) : bool
    + Delete(Guid) : bool
  }
  
  class IncomeService {
    + Context : ApplicationDbContext
    + Create(Income) : bool
    + Read() : [Income]
    + Update(Guid, Income) : bool
    + Delete(Guid) : bool
  }
  
  class ExpenseCategoryService {
    + Context : ApplicationDbContext
    + PredefineCategories() : Void 
    + CreateCategory(String) : Bool
    + ListCategories() : [ExpenseCategory]
  }

  
  class MonthlyBudgeting {
    + Context : ApplicationDbContext
    + VerifyBudgetingStatus() : bool
  }
  
  
  ExpenseCategoryService --* ExpensesService : has a
  ExpensesService --> BaseService  : Implement
  IncomeService --> BaseService  : Implement
  
}

package "User" {
  
  
  class UserManager {
    + userList : [User]
    + Create(User) : bool
    + Read() : [User]
    + Update(Guid, User) : bool
    + Delete(Guid) : bool
  }

  class UserService { 
  + RegisterUser(): IActionResult 
  + LoginUser(): IActionResult 
  + ResetPassword(): IActionResult 
  + GetUserProfile(): User
   }

  
  class PasswordService {
    + EncriptarPassword(String): String
    + VerificarPassword(String, String) : Bool
  }

  class EmailService{
        +SendEmail():bool
  }
  class TokenService{
     +CreateToken():String
  }

  
  UserService --> UserManager : uses 
  UserService --> PasswordService : uses
  UserService --> TokenService : uses
  UserService --> EmailService : uses
  
}

package "Persistence" {
  
  class DbInitializer {
    + Initialize(String) : Void
  }
  
  class DbConstants {
    + DefaultConnectionPath : String 
  }
  
  class UserContext {
    + UserId : Guid
  }
  
  class ApplicationDbContext {
    + UserItems :  DbSet<UserItems>
    + UserGoals :  DbSet<UserGoals>
    + Users : DbSet<User>
  }
  
}

package "RequestPipeLine" {
  class WebApplicationExtension {
    + InitializeDatabase (WebApplication) : WebApplication
  }
}


package "Controllers" {

  class UserContextMiddleWare() {
    + InvokeAsync(HttpContext) : Task 
  }

  class ExpenseController {
    + AddExpense(CreateExpenseRequest) : IActionResult
    + GetAllExpenses() : IActionResult
    + GetExpense() : IActionResult
    + UpdateExpense(CreateExpenseRequest) : IActionResult
    + DeleteExpense() : IActionResult
  }
  
  class IncomeController {
    + AddIncome(CreateIncomeRequest) : IActionResult
    + GetAllIncomes() : IActionResult
    + GetIncome() : IActionResult
    + UpdateIncome(CreateIncomeRequest) : IActionResult
    + DeleteIncome() : IActionResult
  }
  
  class UserController {
    + RegisterUser(CreateUserRequest) : IActionResult
    + Login(String, String) : IActionResult
    + UpdateProfile(CreateUserRequest) : IActionResult
    + ResetPassword(String) : IActionResult
  }
  
  class MonthlySummaryController {
    + SetMonthlyBudget(Decimal, Date): IActionResult
    + GetMonthlySummary(): IActionResult
    + GetMonthlyBudgetStatus() : IActionResult
    + SetSavingGoal(Decimal, Date): IActionResult
    + GetSavingGoal(): IActionResult
  }
}
@enduml
