name: pull-request

on:
  pull_request:
    branches: [ develop ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

      working-directory: src/Ibn
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore


  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

      working-directory: src/Ibn
    - name: Test
      run: |
        dotnet restore
        dotnet test --no-restore --verbosity normal
